#!/usr/bin/env bash

set -e 

script=$(realpath $0)
script_dir=$(dirname "${script}")

echo "mkdir -p \${HOME}/secrets" >> ${BASH_ENV}
echo "export PATH=${script_dir}:\$PATH" >> ${BASH_ENV}
echo "export GCLOUD_CREDENTIALS_FILE=\${HOME}/secrets/gcloud_credentials.json" >> ${BASH_ENV}
echo "export KEYSTORE_PATH=\${HOME}/secrets/jetpackplayground.keystore" >> ${BASH_ENV}
echo "echo \"\${GOOGLE_CLOUD_KEY}\" > \"\${GCLOUD_CREDENTIALS_FILE}\"" >> ${BASH_ENV}
echo "echo \"\${KEYSTORE_VALUE}\" | base64 -d > \"\${KEYSTORE_PATH}\"" >> ${BASH_ENV}